image: node:latest

stages:
  - build
  - test
  - deploy
  #- code_quality # need to create, @Kam, npm test - --with-coverage? for Jest+Enzyme or whatever the flags are

cache: &global_cache
  paths:
    - node_modules/
  policy: pull-push

build:
  stage: build #HERE1
  script:
    - yarn # builds our dependencies (node_modules from package.json and package-lock.json)
  artifacts:
    paths:
      - public
  only:
    refs:
      - merge_requests
      - master

deploy:
  stage: deploy
  # For netlify we must specify the envrironment and its name/url which can be obtianed from site-settings in Netlify
  environment:
    name: production
    url: https://shadow-run.netlify.app
  only:
    - master
  script:
    - npm i -g netlify-cli # here we install a global CLI (command line interface) via npm so that we can deploy to Netlify
    - yarn run build # builds the ts bundle
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

test:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  script:
    - CI=true; yarn test -u # here the CI=true flag is needed so that npm test does not wait for user input (prompts) and just runs the tests
  coverage: /All files\s*\|\s*([\d\.]+)/
